-- ============================================================================
-- appdb schema
-- ============================================================================
-- Structure only. Auto-generated by dev_utils/generate_init_scripts
-- Regenerate from the current database state when schema changes.
-- ============================================================================

--
-- PostgreSQL database dump
--

\restrict KsfxvA2DRBe2Wi4JEtg3FvvaQHHnipBFmfgOBE8hPdZDMZUnrCq9TvqinydxxTp

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.overview_derived DROP CONSTRAINT IF EXISTS overview_derived_new_org_id_fkey;
ALTER TABLE IF EXISTS ONLY public.organization_target_groups DROP CONSTRAINT IF EXISTS organization_target_groups_new_target_group_id_fkey;
ALTER TABLE IF EXISTS ONLY public.organization_target_groups DROP CONSTRAINT IF EXISTS organization_target_groups_new_org_id_fkey;
ALTER TABLE IF EXISTS ONLY public.organization_attachment_types DROP CONSTRAINT IF EXISTS organization_attachment_types_new_org_id_fkey;
ALTER TABLE IF EXISTS ONLY public.organization_attachment_types DROP CONSTRAINT IF EXISTS organization_attachment_types_new_attachment_type_id_fkey;
ALTER TABLE IF EXISTS ONLY public.organization_applicant_types DROP CONSTRAINT IF EXISTS organization_applicant_types_new_org_id_fkey;
ALTER TABLE IF EXISTS ONLY public.organization_applicant_types DROP CONSTRAINT IF EXISTS organization_applicant_types_new_applicant_type_id_fkey;
ALTER TABLE IF EXISTS ONLY public.foundation_vectors DROP CONSTRAINT IF EXISTS foundation_vectors_org_id_e87554a6_fk_organizations_id;
ALTER TABLE IF EXISTS ONLY public.foundation_matches DROP CONSTRAINT IF EXISTS foundation_matches_org_id_a4c68809_fk_organizations_id;
ALTER TABLE IF EXISTS ONLY public.foundation_matches DROP CONSTRAINT IF EXISTS foundation_matches_application_id_c0565987_fk_applicati;
ALTER TABLE IF EXISTS ONLY public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;
ALTER TABLE IF EXISTS ONLY public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_content_type_id_c4bce8eb_fk_django_co;
ALTER TABLE IF EXISTS ONLY public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;
ALTER TABLE IF EXISTS ONLY public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;
ALTER TABLE IF EXISTS ONLY public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;
ALTER TABLE IF EXISTS ONLY public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_group_id_97559544_fk_auth_group_id;
ALTER TABLE IF EXISTS ONLY public.auth_permission DROP CONSTRAINT IF EXISTS auth_permission_content_type_id_2f476e4b_fk_django_co;
ALTER TABLE IF EXISTS ONLY public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
ALTER TABLE IF EXISTS ONLY public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
DROP INDEX IF EXISTS public.foundation_matches_org_id_a4c68809;
DROP INDEX IF EXISTS public.foundation_matches_application_id_c0565987;
DROP INDEX IF EXISTS public.django_session_session_key_c0390e0f_like;
DROP INDEX IF EXISTS public.django_session_expire_date_a5c62663;
DROP INDEX IF EXISTS public.django_admin_log_user_id_c564eba6;
DROP INDEX IF EXISTS public.django_admin_log_content_type_id_c4bce8eb;
DROP INDEX IF EXISTS public.auth_user_username_6821ab7c_like;
DROP INDEX IF EXISTS public.auth_user_user_permissions_user_id_a95ead1b;
DROP INDEX IF EXISTS public.auth_user_user_permissions_permission_id_1fbb5f2c;
DROP INDEX IF EXISTS public.auth_user_groups_user_id_6a12ed8b;
DROP INDEX IF EXISTS public.auth_user_groups_group_id_97559544;
DROP INDEX IF EXISTS public.auth_permission_content_type_id_2f476e4b;
DROP INDEX IF EXISTS public.auth_group_permissions_permission_id_84c5c92e;
DROP INDEX IF EXISTS public.auth_group_permissions_group_id_b120cbf9;
DROP INDEX IF EXISTS public.auth_group_name_a6ea08ec_like;
ALTER TABLE IF EXISTS ONLY public.target_groups DROP CONSTRAINT IF EXISTS target_groups_new_slug_key;
ALTER TABLE IF EXISTS ONLY public.target_groups DROP CONSTRAINT IF EXISTS target_groups_new_pkey;
ALTER TABLE IF EXISTS ONLY public.overview_derived DROP CONSTRAINT IF EXISTS overview_derived_new_pkey;
ALTER TABLE IF EXISTS ONLY public.organizations DROP CONSTRAINT IF EXISTS organizations_new_pkey;
ALTER TABLE IF EXISTS ONLY public.organizations DROP CONSTRAINT IF EXISTS organizations_new_org_key_key;
ALTER TABLE IF EXISTS ONLY public.organization_target_groups DROP CONSTRAINT IF EXISTS organization_target_groups_new_pkey;
ALTER TABLE IF EXISTS ONLY public.organization_target_groups DROP CONSTRAINT IF EXISTS organization_target_groups_new_org_id_target_group_id_key;
ALTER TABLE IF EXISTS ONLY public.organization_attachment_types DROP CONSTRAINT IF EXISTS organization_attachment_types_new_pkey;
ALTER TABLE IF EXISTS ONLY public.organization_attachment_types DROP CONSTRAINT IF EXISTS organization_attachment_types_new_org_id_attachment_type_id_key;
ALTER TABLE IF EXISTS ONLY public.organization_applicant_types DROP CONSTRAINT IF EXISTS organization_applicant_types_new_pkey;
ALTER TABLE IF EXISTS ONLY public.organization_applicant_types DROP CONSTRAINT IF EXISTS organization_applicant_types_new_org_id_applicant_type_id_key;
ALTER TABLE IF EXISTS ONLY public.foundation_vectors DROP CONSTRAINT IF EXISTS foundation_vectors_pkey;
ALTER TABLE IF EXISTS ONLY public.foundation_vectors DROP CONSTRAINT IF EXISTS foundation_vectors_org_id_key;
ALTER TABLE IF EXISTS ONLY public.foundation_matches DROP CONSTRAINT IF EXISTS foundation_matches_pkey;
ALTER TABLE IF EXISTS ONLY public.foundation_matches DROP CONSTRAINT IF EXISTS foundation_matches_application_org_unique;
ALTER TABLE IF EXISTS ONLY public.django_session DROP CONSTRAINT IF EXISTS django_session_pkey;
ALTER TABLE IF EXISTS ONLY public.django_migrations DROP CONSTRAINT IF EXISTS django_migrations_pkey;
ALTER TABLE IF EXISTS ONLY public.django_content_type DROP CONSTRAINT IF EXISTS django_content_type_pkey;
ALTER TABLE IF EXISTS ONLY public.django_content_type DROP CONSTRAINT IF EXISTS django_content_type_app_label_model_76bd3d3b_uniq;
ALTER TABLE IF EXISTS ONLY public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_user DROP CONSTRAINT IF EXISTS auth_user_username_key;
ALTER TABLE IF EXISTS ONLY public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_user_id_permission_id_14a6b632_uniq;
ALTER TABLE IF EXISTS ONLY public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_user DROP CONSTRAINT IF EXISTS auth_user_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_user_id_group_id_94350c0c_uniq;
ALTER TABLE IF EXISTS ONLY public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_permission DROP CONSTRAINT IF EXISTS auth_permission_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_permission DROP CONSTRAINT IF EXISTS auth_permission_content_type_id_codename_01ab375a_uniq;
ALTER TABLE IF EXISTS ONLY public.auth_group DROP CONSTRAINT IF EXISTS auth_group_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissions_pkey;
ALTER TABLE IF EXISTS ONLY public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
ALTER TABLE IF EXISTS ONLY public.auth_group DROP CONSTRAINT IF EXISTS auth_group_name_key;
ALTER TABLE IF EXISTS ONLY public.attachment_types DROP CONSTRAINT IF EXISTS attachment_types_pkey;
ALTER TABLE IF EXISTS ONLY public.attachment_types DROP CONSTRAINT IF EXISTS attachment_types_label_key;
ALTER TABLE IF EXISTS ONLY public.application_sessions DROP CONSTRAINT IF EXISTS application_sessions_pkey;
ALTER TABLE IF EXISTS ONLY public.applicant_types DROP CONSTRAINT IF EXISTS applicant_types_pkey;
ALTER TABLE IF EXISTS ONLY public.applicant_types DROP CONSTRAINT IF EXISTS applicant_types_label_key;
ALTER TABLE IF EXISTS public.target_groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.organizations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.organization_target_groups ALTER COLUMN join_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.organization_attachment_types ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.organization_applicant_types ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.target_groups_new_id_seq;
DROP TABLE IF EXISTS public.target_groups;
DROP TABLE IF EXISTS public.overview_derived;
DROP SEQUENCE IF EXISTS public.organizations_new_id_seq;
DROP TABLE IF EXISTS public.organizations;
DROP SEQUENCE IF EXISTS public.organization_target_groups_new_join_id_seq;
DROP TABLE IF EXISTS public.organization_target_groups;
DROP SEQUENCE IF EXISTS public.organization_attachment_types_new_id_seq;
DROP TABLE IF EXISTS public.organization_attachment_types;
DROP SEQUENCE IF EXISTS public.organization_applicant_types_new_id_seq;
DROP TABLE IF EXISTS public.organization_applicant_types;
DROP TABLE IF EXISTS public.foundation_vectors;
DROP TABLE IF EXISTS public.foundation_matches;
DROP TABLE IF EXISTS public.django_session;
DROP TABLE IF EXISTS public.django_migrations;
DROP TABLE IF EXISTS public.django_content_type;
DROP TABLE IF EXISTS public.django_admin_log;
DROP TABLE IF EXISTS public.auth_user_user_permissions;
DROP TABLE IF EXISTS public.auth_user_groups;
DROP TABLE IF EXISTS public.auth_user;
DROP TABLE IF EXISTS public.auth_permission;
DROP TABLE IF EXISTS public.auth_group_permissions;
DROP TABLE IF EXISTS public.auth_group;
DROP TABLE IF EXISTS public.attachment_types;
DROP TABLE IF EXISTS public.application_sessions;
DROP TABLE IF EXISTS public.applicant_types;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: applicant_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applicant_types (
    applicant_type_id text NOT NULL,
    label text NOT NULL
);


--
-- Name: application_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_sessions (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    applicant_kind character varying(20),
    field_1 text,
    field_2 text,
    field_3 text,
    layer1_passed_org_ids jsonb,
    application_vector double precision[],
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: application_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachment_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachment_types (
    attachment_type_id text NOT NULL,
    label text NOT NULL
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: foundation_matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.foundation_matches (
    id bigint NOT NULL,
    similarity_score double precision NOT NULL,
    match_level character varying(10) NOT NULL,
    application_id bigint NOT NULL,
    org_id integer NOT NULL
);


--
-- Name: foundation_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.foundation_matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.foundation_matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: foundation_vectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.foundation_vectors (
    id bigint NOT NULL,
    vector double precision[] NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    org_id integer NOT NULL
);


--
-- Name: foundation_vectors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.foundation_vectors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.foundation_vectors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_applicant_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_applicant_types (
    id bigint NOT NULL,
    org_id integer NOT NULL,
    applicant_type_id text NOT NULL
);


--
-- Name: organization_applicant_types_new_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.organization_applicant_types_new_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: organization_applicant_types_new_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.organization_applicant_types_new_id_seq OWNED BY public.organization_applicant_types.id;


--
-- Name: organization_attachment_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_attachment_types (
    id bigint NOT NULL,
    org_id integer NOT NULL,
    attachment_type_id text NOT NULL
);


--
-- Name: organization_attachment_types_new_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.organization_attachment_types_new_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: organization_attachment_types_new_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.organization_attachment_types_new_id_seq OWNED BY public.organization_attachment_types.id;


--
-- Name: organization_target_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_target_groups (
    join_id integer NOT NULL,
    org_id integer NOT NULL,
    target_group_id integer NOT NULL
);


--
-- Name: organization_target_groups_new_join_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.organization_target_groups_new_join_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: organization_target_groups_new_join_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.organization_target_groups_new_join_id_seq OWNED BY public.organization_target_groups.join_id;


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id integer NOT NULL,
    org_key text NOT NULL,
    name text NOT NULL,
    page_start integer,
    description text,
    contact_raw text,
    address text,
    postal_code text,
    city text,
    phone_numbers_jsonb jsonb DEFAULT '[]'::jsonb NOT NULL,
    emails_jsonb jsonb DEFAULT '[]'::jsonb NOT NULL,
    websites_jsonb jsonb DEFAULT '[]'::jsonb NOT NULL,
    target_group_raw text,
    applicants_raw text,
    submission_deadline_raw text,
    submission_address_raw text,
    attachments_raw text,
    raw_sections_jsonb jsonb DEFAULT '{}'::jsonb NOT NULL,
    parse_warning text,
    source_file text
);


--
-- Name: organizations_new_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.organizations_new_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: organizations_new_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.organizations_new_id_seq OWNED BY public.organizations.id;


--
-- Name: overview_derived; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.overview_derived (
    org_id integer NOT NULL,
    name text NOT NULL,
    page integer,
    youth_family boolean DEFAULT false NOT NULL,
    elderly boolean DEFAULT false NOT NULL,
    disability boolean DEFAULT false NOT NULL,
    health boolean DEFAULT false NOT NULL,
    migration boolean DEFAULT false NOT NULL,
    education boolean DEFAULT false NOT NULL,
    poverty boolean DEFAULT false NOT NULL,
    individuals boolean DEFAULT false NOT NULL,
    institutions boolean DEFAULT false NOT NULL,
    exhausted boolean DEFAULT false NOT NULL,
    derived_from text,
    parse_warning text
);


--
-- Name: target_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.target_groups (
    id integer NOT NULL,
    name text NOT NULL,
    slug text NOT NULL
);


--
-- Name: target_groups_new_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.target_groups_new_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: target_groups_new_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.target_groups_new_id_seq OWNED BY public.target_groups.id;


--
-- Name: organization_applicant_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_applicant_types ALTER COLUMN id SET DEFAULT nextval('public.organization_applicant_types_new_id_seq'::regclass);


--
-- Name: organization_attachment_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_attachment_types ALTER COLUMN id SET DEFAULT nextval('public.organization_attachment_types_new_id_seq'::regclass);


--
-- Name: organization_target_groups join_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_target_groups ALTER COLUMN join_id SET DEFAULT nextval('public.organization_target_groups_new_join_id_seq'::regclass);


--
-- Name: organizations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations ALTER COLUMN id SET DEFAULT nextval('public.organizations_new_id_seq'::regclass);


--
-- Name: target_groups id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_groups ALTER COLUMN id SET DEFAULT nextval('public.target_groups_new_id_seq'::regclass);


--
-- Name: applicant_types applicant_types_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applicant_types
    ADD CONSTRAINT applicant_types_label_key UNIQUE (label);


--
-- Name: applicant_types applicant_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applicant_types
    ADD CONSTRAINT applicant_types_pkey PRIMARY KEY (applicant_type_id);


--
-- Name: application_sessions application_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_sessions
    ADD CONSTRAINT application_sessions_pkey PRIMARY KEY (id);


--
-- Name: attachment_types attachment_types_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachment_types
    ADD CONSTRAINT attachment_types_label_key UNIQUE (label);


--
-- Name: attachment_types attachment_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachment_types
    ADD CONSTRAINT attachment_types_pkey PRIMARY KEY (attachment_type_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: foundation_matches foundation_matches_application_org_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_matches
    ADD CONSTRAINT foundation_matches_application_org_unique UNIQUE (application_id, org_id);


--
-- Name: foundation_matches foundation_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_matches
    ADD CONSTRAINT foundation_matches_pkey PRIMARY KEY (id);


--
-- Name: foundation_vectors foundation_vectors_org_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_vectors
    ADD CONSTRAINT foundation_vectors_org_id_key UNIQUE (org_id);


--
-- Name: foundation_vectors foundation_vectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_vectors
    ADD CONSTRAINT foundation_vectors_pkey PRIMARY KEY (id);


--
-- Name: organization_applicant_types organization_applicant_types_new_org_id_applicant_type_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_applicant_types
    ADD CONSTRAINT organization_applicant_types_new_org_id_applicant_type_id_key UNIQUE (org_id, applicant_type_id);


--
-- Name: organization_applicant_types organization_applicant_types_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_applicant_types
    ADD CONSTRAINT organization_applicant_types_new_pkey PRIMARY KEY (id);


--
-- Name: organization_attachment_types organization_attachment_types_new_org_id_attachment_type_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_attachment_types
    ADD CONSTRAINT organization_attachment_types_new_org_id_attachment_type_id_key UNIQUE (org_id, attachment_type_id);


--
-- Name: organization_attachment_types organization_attachment_types_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_attachment_types
    ADD CONSTRAINT organization_attachment_types_new_pkey PRIMARY KEY (id);


--
-- Name: organization_target_groups organization_target_groups_new_org_id_target_group_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_target_groups
    ADD CONSTRAINT organization_target_groups_new_org_id_target_group_id_key UNIQUE (org_id, target_group_id);


--
-- Name: organization_target_groups organization_target_groups_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_target_groups
    ADD CONSTRAINT organization_target_groups_new_pkey PRIMARY KEY (join_id);


--
-- Name: organizations organizations_new_org_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_new_org_key_key UNIQUE (org_key);


--
-- Name: organizations organizations_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_new_pkey PRIMARY KEY (id);


--
-- Name: overview_derived overview_derived_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.overview_derived
    ADD CONSTRAINT overview_derived_new_pkey PRIMARY KEY (org_id);


--
-- Name: target_groups target_groups_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_groups
    ADD CONSTRAINT target_groups_new_pkey PRIMARY KEY (id);


--
-- Name: target_groups target_groups_new_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_groups
    ADD CONSTRAINT target_groups_new_slug_key UNIQUE (slug);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: foundation_matches_application_id_c0565987; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX foundation_matches_application_id_c0565987 ON public.foundation_matches USING btree (application_id);


--
-- Name: foundation_matches_org_id_a4c68809; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX foundation_matches_org_id_a4c68809 ON public.foundation_matches USING btree (org_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: foundation_matches foundation_matches_application_id_c0565987_fk_applicati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_matches
    ADD CONSTRAINT foundation_matches_application_id_c0565987_fk_applicati FOREIGN KEY (application_id) REFERENCES public.application_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: foundation_matches foundation_matches_org_id_a4c68809_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_matches
    ADD CONSTRAINT foundation_matches_org_id_a4c68809_fk_organizations_id FOREIGN KEY (org_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: foundation_vectors foundation_vectors_org_id_e87554a6_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foundation_vectors
    ADD CONSTRAINT foundation_vectors_org_id_e87554a6_fk_organizations_id FOREIGN KEY (org_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organization_applicant_types organization_applicant_types_new_applicant_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_applicant_types
    ADD CONSTRAINT organization_applicant_types_new_applicant_type_id_fkey FOREIGN KEY (applicant_type_id) REFERENCES public.applicant_types(applicant_type_id) ON DELETE CASCADE;


--
-- Name: organization_applicant_types organization_applicant_types_new_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_applicant_types
    ADD CONSTRAINT organization_applicant_types_new_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- Name: organization_attachment_types organization_attachment_types_new_attachment_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_attachment_types
    ADD CONSTRAINT organization_attachment_types_new_attachment_type_id_fkey FOREIGN KEY (attachment_type_id) REFERENCES public.attachment_types(attachment_type_id) ON DELETE CASCADE;


--
-- Name: organization_attachment_types organization_attachment_types_new_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_attachment_types
    ADD CONSTRAINT organization_attachment_types_new_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- Name: organization_target_groups organization_target_groups_new_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_target_groups
    ADD CONSTRAINT organization_target_groups_new_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- Name: organization_target_groups organization_target_groups_new_target_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_target_groups
    ADD CONSTRAINT organization_target_groups_new_target_group_id_fkey FOREIGN KEY (target_group_id) REFERENCES public.target_groups(id) ON DELETE CASCADE;


--
-- Name: overview_derived overview_derived_new_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.overview_derived
    ADD CONSTRAINT overview_derived_new_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict KsfxvA2DRBe2Wi4JEtg3FvvaQHHnipBFmfgOBE8hPdZDMZUnrCq9TvqinydxxTp

