# Generated by Django 6.0.3 on 2026-03-28 09:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantType',
            fields=[
                ('applicant_type_id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'applicant type',
                'verbose_name_plural': 'applicant types',
                'db_table': 'applicant_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('attachment_type_id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'attachment type',
                'verbose_name_plural': 'attachment types',
                'db_table': 'attachment_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('page_start', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_raw', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone_numbers_jsonb', models.JSONField(default=list)),
                ('emails_jsonb', models.JSONField(default=list)),
                ('websites_jsonb', models.JSONField(default=list)),
                ('target_group_raw', models.TextField(blank=True, null=True)),
                ('applicants_raw', models.TextField(blank=True, null=True)),
                ('submission_deadline_raw', models.TextField(blank=True, null=True)),
                ('submission_address_raw', models.TextField(blank=True, null=True)),
                ('attachments_raw', models.TextField(blank=True, null=True)),
                ('raw_sections_jsonb', models.JSONField(default=dict)),
                ('parse_warning', models.TextField(blank=True, null=True)),
                ('source_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationApplicantType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'organization_applicant_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAttachmentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'organization_attachment_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationTargetGroup',
            fields=[
                ('join_id', models.AutoField(db_column='join_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'organization_target_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'target group',
                'verbose_name_plural': 'target groups',
                'db_table': 'target_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('applicant_kind', models.CharField(blank=True, choices=[('individual', 'Individual'), ('institution', 'Institution')], max_length=20, null=True)),
                ('field_1', models.TextField(blank=True, null=True)),
                ('field_2', models.TextField(blank=True, null=True)),
                ('field_3', models.TextField(blank=True, null=True)),
                ('layer1_passed_org_ids', models.JSONField(blank=True, null=True)),
                ('application_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application_sessions',
            },
        ),
        migrations.CreateModel(
            name='OverviewDerived',
            fields=[
                ('org', models.OneToOneField(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='overview', serialize=False, to='fonds.organization')),
                ('name', models.TextField()),
                ('page', models.IntegerField(blank=True, null=True)),
                ('youth_family', models.BooleanField(default=False)),
                ('elderly', models.BooleanField(default=False)),
                ('disability', models.BooleanField(default=False)),
                ('health', models.BooleanField(default=False)),
                ('migration', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('poverty', models.BooleanField(default=False)),
                ('individuals', models.BooleanField(default=False)),
                ('institutions', models.BooleanField(default=False)),
                ('exhausted', models.BooleanField(default=False)),
                ('derived_from', models.TextField(blank=True, null=True)),
                ('parse_warning', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'overview_derived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoundationVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foundation_vector', to='fonds.organization')),
            ],
            options={
                'db_table': 'foundation_vectors',
            },
        ),
        migrations.CreateModel(
            name='FoundationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('match_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fonds.applicationsession')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundation_matches', to='fonds.organization')),
            ],
            options={
                'db_table': 'foundation_matches',
                'constraints': [models.UniqueConstraint(fields=('application', 'org'), name='foundation_matches_application_org_unique')],
            },
        ),
    ]
