# Generated by Django 6.0.3 on 2026-04-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsession',
            old_name='field_1',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='applicationsession',
            old_name='field_2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='applicationsession',
            old_name='field_3',
            new_name='residency_status',
        ),
        migrations.RemoveField(
            model_name='applicationsession',
            name='applicant_kind',
        ),
        migrations.AddField(
            model_name='applicationsession',
            name='support_type',
            field=models.CharField(blank=True, choices=[('private', 'Private individual'), ('institution', 'Institution'), ('project', 'Project funding'), ('education', 'Education funding')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationsession',
            name='zip_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
